apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: detect-spoke-cluster
spec:
  collectResources: true
  resourceSelectors:
  - group: "lib.projectsveltos.io"
    version: "v1beta1"
    kind: "SveltosCluster"
    labelFilters:
    - key: type
      operation: Equal
      value: spoke
